### ISSUE TITLE
`pkgload` no longer working after updating to `rlang 0.4.0`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgload#102]
This affects the entire `tidyverse` ecosystem on my computer; I can't even provide a `reprex` because `reprex` package fails to load as well.

cc @lionel- 

```r
> library(pkgload)
Error: package or namespace load failed for ‘pkgload’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: is_string(x)
  error: object 'rlang_is_string' not found
```

Here is my session information:
```
#> - Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#>  setting  value                                    
#>  version  R version 3.6.0 alpha (2019-03-29 r76300)
#>  os       Windows 10 x64                           
#>  system   x86_64, mingw32                          
#>  ui       RTerm                                    
#>  language (EN)                                     
#>  collate  English_United States.1252               
#>  ctype    English_United States.1252               
#>  tz       America/New_York                         
#>  date     2019-06-25
```

**Comment by lionel-** [comment]
This is typical of silent installation failures on Windows. On this platform, DLLs can't be copied over if they are already in use. The manifestation of this is a warning and a broken package.

Please close all your R and RStudio sessions before installing rlang. If you install it from github, use the {remotes} package which doesn't depend on rlang and thus won't load it in your session:

```r
remotes::install_github("r-lib/rlang")
```

Also check rlang isn't automatically loaded from your RProfile when you start a session.

**Comment by gaborcsardi** [comment]
Unfortunately, that's not enough, because remotes does load rlang, if it is available. See https://github.com/r-lib/remotes#standalone-mode

**Comment by jimhester** [comment]
Can confirm this is almost certainly because of a failure during rlang installation, I verified rlang 0.4.0 works with pkgload on both windows and macOS.

**Comment by IndrajeetPatil** [comment]
Thanks for the quick response!

 I can confirm that removing the older version, deleting the `00LOCK` folder, closing and reopening RStudio, and then installing the CRAN version of `rlang` solved this issue.
