### ISSUE TITLE
Can't load_all() if target package is in Depends of an attached package

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgload#103]
This is admittedly a rare situation, but matters deeply to me 😬

I work a lot on usethis, using devtools and, therefore, calling `pkgload::load_all()`.

I also attach devtools in all interactive sessions via `.Rprofile`.

Until very recently, devtools made all usethis functions available in a rather unconventional way:

https://github.com/r-lib/devtools/commit/d8b12e8fe022be1931a72cacd92723d32c0d0e9d#diff-e549505eb95036528ca3b125f62915a6

But in the version of devtools currently in the queue at CRAN, devtools simply puts usethis in Depends.

And this breaks a simple `load_all()` workflow:

```
> devtools::load_all(".")
Loading usethis
unloadNamespace("usethis") not successful, probably because another loaded package depends on it. Forcing unload. If you encounter problems, please restart R.
✔ Setting active project to '/Users/jenny/rrr/usethis'
Error in importIntoEnv(pkgenv, exports, nsenv, exports) : 
  cannot change value of locked binding for 'proj_get'
```

The message about unsuccessful `unloadNamespace()` had always been there, btw. It's the `Error in importIntoEnv()` that is new.

Here is the workaround:

```
> pkgload::unload("devtools")
> devtools::load_all(".")
Loading usethis
unloadNamespace("usethis") not successful, probably because another loaded package depends on it. Forcing unload. If you encounter problems, please restart R.
✔ Setting active project to '/Users/jenny/rrr/usethis'
> attachNamespace("devtools")
```

@jimhester suggested I record this here, to think about whether and how to address in pkgload.

**Comment by hadley** [comment]
Looks like this is fixed with dev pkgload?

**Comment by jennybc** [comment]
Yeah this has been sorted out already, in #130, I believe.
