### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by ms609** [r-lib/pkgload#106]
I notice that the DESCRIPTION file on GitHub lists version 1.0.1.9000, CRAN has 1.0.2 (and the github devtools repo requires >=1.0.2).

This caused me some confusion when testing other packages using Travis; I'd included r_github_packages: r-lib/pkgload as well as r-lib/devtools, and gotten confused as to why I was encountering errors.

Is it possible to include a pointer to the most up-to-date source code here, or in the readme?

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/pkgload/commit/78e7e3acf775268ccf58f420e228541fd549877a
