### ISSUE TITLE
load_all() fails when R files in data/ use functions that aren't qualified by namespace

### ISSUE THREAD

**Issue by gsrohde** [r-lib/pkgload#111]
For example, if I have a call to `read.delim` in an R file in `data/`, I have no problem installing the package using `R CMD INSTALL`.  But if I attempt to run `pkgload::load_all()`, the function can't be found unless I replace the call with `utils::read.delim`.  (This is related to issue https://github.com/r-lib/pkgload/issues/87.)

Moreover, the documentation for `load_all` is slightly misleading.  The first item in the Details section states "Loads all data files in data/. See load_data() for more details."  But the description for `load_data` states that it loads all _.RData_ files in the data directory and doesn't mention `.R` files or '.csv' files.

**Comment by jimhester** [comment]
I would suggest you qualify your calls as you suggest, this seems unlikely to be fixed in pkgload.
