### ISSUE TITLE
backticks can break load_all(), devtools::document()

### ISSUE THREAD

**Issue by chasemc** [r-lib/pkgload#117]
Don't know if this is fixable or not, I at least wanted to document this behavior/error message. 

If a single back tick is mistakenly outside a function for a package a source line is provided:
```
> devtools::load_all(".")
Loading IDBacApp
Error in parse(text = lines, n = -1, srcfile = srcfile) : 
  C:/Users/CMC/Documents/GitHub/IDBac_App/R/getPeakData.R:69:2: unexpected INCOMPLETE_STRING
68:   
69: }`
     ^
```

However, if two backticks are present no line # is provided.
```
> devtools::load_all(".")
Loading IDBacApp
Error in parse(text = lines, n = -1, srcfile = srcfile) : 
  attempt to use zero-length variable name
```

**Comment by jimhester** [comment]
These errors are caused by the R parser, there isn't really anything we can do about them in pkgload.
