### ISSUE TITLE
Unable to load package that depends on package loaded by load_all

### ISSUE THREAD

**Issue by hongooi73** [r-lib/pkgload#121]
Say you're working on a package A, that has a reverse dependency B which lists A in `Depends:` (rather than `Imports:`).

If you load A with `load_all()`, and then do `library(B)`, the latter will fail with

```
Error: package 'A' required by 'B' could not be found
```

To reproduce this, you can use the foreach package, which is at https://github.com/RevolutionAnalytics/foreach

- Clone the repo
- Run
```
load_all()
library(doParallel)
```
This will result in the error message above.

Running a traceback shows that the error comes from `base::.getRequiredPackages2`. This function is called by `base::library`, and in turn calls `system.file` to get the path to one of foreach's package files. But when foreach is loaded via `load_all`, there are no package files and everything falls down.

**Comment by jimhester** [comment]
Another example of this is

```r
pkgload::load_all("xml2")
library(rvest)
```
