### ISSUE TITLE
Why does pkgload:::print.dev_topic() set no_links = TRUE?

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgload#123]

**Comment by jimhester** [comment]
It seems to have been added by [you 8 years ago](https://github.com/r-lib/pkgload/commit/1e8d81f754258e6df2a598fed1a35cb33de5d2ae#diff-ebc66cae9740358a0c5726fa771285feR65-R66), maybe ask them ;)

**Comment by hadley** [comment]
I think we should probably reconsider this, or at least experiment with what happens when we remove it. (The links might not work, but at least having them there would be helpful)

**Comment by hadley** [comment]
This code isn't usually called because we use RStudio's `previewRd`. I took a quick look through the RStudio source code and couldn't find any use of `Rd2HTML` or `no_links`.

**Comment by hadley** [comment]
Ah because RStudio [uses Rdconv](https://github.com/rstudio/rstudio/commit/031cc79a15aade8137e65821805abd9d14b355ac#diff-2a451ed4dadb7ca8b0875ca17641029dR608) and the `no_links` argument has "logical: suppress hyperlinks to other help topics. Used by R CMD Rdconv."

So I don't think this is possible to fix.
