### ISSUE TITLE
Question regarding DEVTOOLS_LOAD

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgload#134]
In the [docs](https://r-lib.github.io/pkgload/reference/load_all.html#details) I see "devtools sets the DEVTOOLS_LOAD environment variable to "true" to let you check whether the helpers are run during package loading." which makes it sound as if one could use the environment variable to change the behavior but I see

https://github.com/r-lib/pkgload/blob/d404ed9131f5edf064470c6da0b8efca9572bb01/R/load.r#L232

So actually one can only use the `helpers` argument of `load_all()` to choose not to load testthat helpers?

**Comment by maelle** [comment]
What actually needs the environment variable? https://github.com/search?l=R&q=DEVTOOLS_LOAD&type=code

**Comment by jimhester** [comment]
It was added in https://github.com/r-lib/devtools/pull/1391. I think the idea was to allow you to be able to query whether the helpers were run or not. I don't think any external code uses it, though maybe @lionel- has some personal code that does.

**Comment by lionel-** [comment]
IIRC it was for vdiffr but I think I found a better way than `DEVTOOLS_LOAD` in the end.

**Comment by maelle** [comment]
my confusion comes from the fact that from what I understand

* At the moment no code uses the environment variable
* When it comes up in pkgload, it's set to TRUE via withr.

So is it useless? I could well be missing something. :slightly_smiling_face:

**Comment by lionel-** [comment]
Since testthat also uses pkgload to set up the test environment, I'm not sure you can actually use that envvar to branch out anything. So it might well be useless.

**Comment by gaborcsardi** [comment]
testthat does not use pkgload (by default) for `test_check()`, i.e. in `R CMD check`

**Comment by dmurdoch** [comment]
`devtools::load_all()` fails to load `rgl`, because my `.onLoad` function does some tricky stuff to decide which DLL to load.  I was hoping there was an easy way to detect I was in `load_all()` so I could work in both environments, but `DEVTOOLS_LOAD` doesn't appear to be set.  Is there some other test I can use?

**Comment by lionel-** [comment]
I recently needed a way to detect that code is running during `load_all()` to disable a call to `browser()` in that case. It'd be nice to have an interface for this.

**Comment by gaborcsardi** [comment]
I think there is a way, it is `pkgload::is_dev_package()`.
