### ISSUE TITLE
.Rbuildignore not respected when loading package.

### ISSUE THREAD

**Issue by mcol** [r-lib/pkgload#137]
If I have a `filename_to_be_ignored.R` inside the R directory, this file gets loaded by `load_code()` even if the package's `.Rbuildignore` contains a line such as
```
_to_be_ignored.R
```

Presumaby the `.Rbuildignore` patterns should be discarded by `find_code()` or within `load_code()` itself.

**Comment by jimhester** [comment]
Couldn't you just put the file anywhere else on your file system instead?

**Comment by mcol** [comment]
I'd like to have different package contents (say one for distribution and one for internal testing) so that either could be loaded up with `devtools::document()` with minimal change. While `roxygen2` respects the ignore patterns, as soon as it delegates to `pkgload` those are not considered.

**Comment by lionel-** [comment]
This feature seems a bit too specific. I'd be happy to review a PR with unit tests though.

Closing for now but if other people need this feature please feel free to comment.
