### ISSUE TITLE
`object 'lev' not found` when loading packages with S4 classes

### ISSUE THREAD

**Issue by mtmorgan** [r-lib/pkgload#139]
Trying to `devtools::load_all()` an S4 package with recent R-devel leads to an error
```
Error in add_classes_to_exports(ns = nsenv, package = package, exports = exports,  :
  object 'lev' not found
> traceback()
4: add_classes_to_exports(ns = nsenv, package = package, exports = exports,
       nsInfo = nsInfo)
3: setup_ns_exports(path, export_all, export_imports)
2: pkgload::load_all(path = path, reset = reset, recompile = recompile,
       export_all = export_all, helpers = helpers, quiet = quiet,
       ...)
1: devtools::load_all()
```
This seems to be from https://github.com/r-lib/pkgload/blob/161ba01e1c02ddc462bb6780b7bec30a2c9cd369/R/namespace-env.r#L148 leading to
```
> head(pkgload:::add_classes_to_exports, 7)

1 function (ns, package, exports, nsInfo)
2 {
3     hasS4m <- .hasS4MetaData(ns)
4     if (.isMethodsDispatchOn() && hasS4m && !identical(package,
5         "methods")) {
6         if (lev > 1L || lev == -5)
7             message("-- processing S4 stuff for ", dQuote(package))
```
where `lev` would indeed appear not to be defined. Perhaps recent changes to base::loadNamespace https://github.com/wch/r-source/commits/trunk/src/library/base/R/namespace.R

A relatively easy example is
```
git clone --depth 1 https://github.com/Bioconductor/BiocGenerics
R -e "devtools::load_all('BiocGenerics')"
```
with R Under development (unstable) (2021-02-05 r79944) -- "Unsuffered Consequences"

**Comment by mtmorgan** [comment]
Hmm I guess this is fixed in https://github.com/r-lib/pkgload/commit/161ba01e1c02ddc462bb6780b7bec30a2c9cd369 so the issue is that this is not available on CRAN...

**Comment by hadley** [comment]
Just to close the loop on this #140 is tracking the release, which is a bit delayed because of current CRAN issues.
