### ISSUE TITLE
Packaged don't find vignettes created with use-vignette

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgload#14]
<a href="https://github.com/smach"><img src="https://avatars2.githubusercontent.com/u/3394160?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smach](https://github.com/smach)**
_Thursday Sep 17, 2015 at 00:53 GMT_
_Originally opened as https://github.com/hadley/devtools/issues/931_

----

Packages don't "find" vignettes created with use-vignette() -- that is, they're not listed in the package help or when runningvignette() and browseVignettes() -- without also running build_vignette(). Issue filed per this Twitter thread https://twitter.com/sharon000/status/644256000451694592

**Comment by jimhester** [comment]
<a href="https://github.com/jennybc"><img src="https://avatars0.githubusercontent.com/u/599454?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jennybc](https://github.com/jennybc)**
_Thursday Nov 12, 2015 at 10:22 GMT_

----

What IS the official party line on how to manage vignettes during development?

In your book, [vignette workflow](http://r-pkgs.had.co.nz/vignettes.html#vignette-workflow) addresses the (ephemeral) preview. And [development cycle](http://r-pkgs.had.co.nz/vignettes.html#vignette-workflow-2) gets at the other end ... when building and installing a package properly.

What about the bit in the middle?

**Comment by jimhester** [comment]
<a href="https://github.com/hadley"><img src="https://avatars0.githubusercontent.com/u/4196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hadley](https://github.com/hadley)**
_Thursday Nov 12, 2015 at 12:49 GMT_

----

I preview them with Cmd + Shift + K. What else do you need to do during dev?

**Comment by jimhester** [comment]
<a href="https://github.com/jennybc"><img src="https://avatars0.githubusercontent.com/u/599454?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jennybc](https://github.com/jennybc)**
_Thursday Nov 12, 2015 at 16:02 GMT_

----

I'm thinking about the vignettes relative to what we do for roxygen comment / Rd file (and README.Rmd / README.md?).

The [documentation workflow](http://r-pkgs.had.co.nz/man.html#man-workflow) results in persistent help files you can preview in their natural habitat with `?`. What's the equivalent for a vignette? The Cmd + Shift + K preview can be a drag because sometimes they take a long time to render.

It's not that I can't figure out how get a rendered vignette. It's about figuring out the most `devtools`-ish way to get and possibly hold on to them.

**Comment by jimhester** [comment]
<a href="https://github.com/hadley"><img src="https://avatars0.githubusercontent.com/u/4196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hadley](https://github.com/hadley)**
_Thursday Nov 12, 2015 at 19:11 GMT_

----

Oh hmmmm, maybe we need a `vignette()` shim to get the dev version?

**Comment by hadley** [comment]
I think this needs a fix to install: https://github.com/hadley/devtools/issues/1578
