### ISSUE TITLE
Loading when the package name is invalid

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/pkgload#147]
I'm very interested in using `DESCRIPTION` files for non-package projects. One of my favorite benefits is being able to `load_all()`. Unfortunately, if the name of the project is not a valid R package name, `load_all()` errors. IMO, it shouldn't be `load_all()`'s job to check the name, but having read the source code, I see it's a bit more complicated than that:

https://github.com/r-lib/pkgload/blob/21675ecdf06750680f0ab7055733e2111279b6cd/R/load.r#L123-L131

As it's actually tools running a more complete check on the `DESCRIPTION` file.

Ignoring the fact that I could get around this by sanitizing the name in the `DESCRIPTION` file, is there another approach that could be used here to facilitate better use of loading in non-package projects? E.g. run a more custom check on the `DESCRIPTION` file with desc or capture and ignore (or just warn) when the problem is not a big deal (like the name)?

Edit: Actually, now that I'm looking at `tools:::.check_package_description()`, this seems like stuff that would all be caught in R CMD check anyway. Does something this complete need to be run at the loading stage?

**Comment by jimhester** [comment]
I think we can remove it. While it may catch some uses for load_all() in the wrong directory the tools code doesn't actually throw an error in many cases.

Possibly we could just call `rprojroot::find_package_root_file()` to find the package root, erroring otherwise.

All it does is check there is a description starting with `^Package: `

**Comment by malcolmbarrett** [comment]
That sounds perfect to me. Happy to PR if you want

**Comment by jimhester** [comment]
Sure a PR would be great
