### ISSUE TITLE
Function ".onUnload" is not executed when "load_all" is called

### ISSUE THREAD

**Issue by nextpagesoft** [r-lib/pkgload#148]
Hi, version 1.2 does not execute `.onUnload` function if defined within an R package. I'm not sure this an intended behaviour as this means that any clean up code a package maintainer defined is not executed. For instance `shiny::removeInputHandler` is commonly placed in `.onUnload` to clean up after `shiny::registerInputHandler` in `.onLoad`.

Steps to reproduce:
1. Create a bare minimal R package
2. Define `.onLoad` and `.onUload` as:
```r
.onLoad <- function(libname, pkgname) {
  print('.onLoad')

  invisible(NULL)
}

.onUnload <- function(libname, pkgname) {
  print('.onUnload')

  invisible(NULL)
}
```
3. Execute `pkgload::load_all(".")`. Only `".onLoad"` is printed regardless of value provided for argument `reset`.

**Comment by jimhester** [comment]
It does if you explicitly call `unload()`, however `pkgload::load_all()` no longer fully unloads the namespace as of https://github.com/r-lib/pkgload/pull/133, as doing so can cause crashes for packages using compiled code.

So this is working as designed. If your usage is assuming the uload is called you will need to explicitly call `unload()` before running `load_all()`.
