### ISSUE TITLE
Cannot `load_all()` desc, possible regression in 1.2.0

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgload#150]
```r
❯ pkgload::load_all()
ℹ Loading desc
Error in create_ns_env(path) : Namespace for desc already exists.

❯ pkgload::load_all()
ℹ Loading desc
Error in intersect(names(private$data), dep_types) :
  object 'dep_types' not found
```

**Comment by NLDLEW1** [comment]
I believe this is related to https://github.com/r-lib/pkgload/issues/148. Unloading is not clean.

**Comment by gaborcsardi** [comment]
@NLDLEW1 There is no `.onUnload()` in desc, so I would think not? It also fails for me if desc is not loaded at all.

OTOH maybe it is related to pkgload importing desc.

**Comment by jimhester** [comment]
Yes, I encountered a similar problem with withr with the current pkgload, it only really affects functions who are used within pkgload. I think you will just have do deal with it or use the older version of pkgload when interactively developing desc unfortunately.
