### ISSUE TITLE
pkgload 1.1.0 requires rlang 0.4.9?

### ISSUE THREAD

**Issue by brianrepko** [r-lib/pkgload#152]
I'm doing a `renv::restore(clean=TRUE)` on a project that works for most folks - but for one person, I'm getting the following error when installing pkgload v 1.1.0

No idea why pkgload 1.1.0 would require rlang 0.4.9 - it is not in the DESCRIPTION file like that.
And all the dependencies are logged in the renv.lock file as old versions.

In particular withr is 2.3.0, desc is 1.2.0, rprojroot is 1.3-2, testthat is 2.3.2
```
* installing to library ‘/tmp/Rtmpz1LU4f/renv-staging-40576339e478’
* installing *source* package ‘pkgload’ ...
** package ‘pkgload’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/prog/R/3.6.1-foss-2018a/lib64/R/include" -DNDEBUG   -I/usr/prog/OpenBLAS/0.2.20-GCC-6.4.0-2.28/include -I/usr/prog/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/include -I/usr/prog/FFTW/3.3.7-gompi-2018a/include -I/usr/prog/Java/1.8.0_162/include  -fpic  -O2 -march=x86-64 -mtune=generic -fPIC  -c unlock.c -o unlock.o
gcc -shared -L/usr/prog/R/3.6.1-foss-2018a/lib64/R/lib -L/usr/prog/GCCcore/6.4.0/lib64 -L/usr/prog/GCCcore/6.4.0/lib -L/usr/prog/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib -L/usr/prog/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/lib -L/usr/prog/FFTW/3.3.7-gompi-2018a/lib -L/usr/prog/Java/1.8.0_162/lib -o pkgload.so unlock.o -L/usr/prog/R/3.6.1-foss-2018a/lib64/R/lib -lR
installing to /tmp/Rtmpz1LU4f/renv-staging-40576339e478/00LOCK-pkgload/00new/pkgload/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘pkgload’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.9 is required
Error: loading failed
Execution halted
ERROR: loading failed
```

**Comment by brianrepko** [comment]
all the dependent libraries get installed prior to pkgload - except testthat 2.3.2 - and so I wondering if there is something in the onload that is doing something with testthat and that is forcing the 3.0.1 / 3.0.2 version of testthat which requires rlang 0.4.9

**Comment by jimhester** [comment]
Yes, we explicitly load testthat in `.onLoad()`. I would guess you would see a similar issue just loading testthat directly without pkgload.

**Comment by brianrepko** [comment]
right - I can see that in R/zzz.R - but that just looks at the existing library correct? (which wouldn't have testthat installed yet).
this might be a renv issue then...

**Comment by brianrepko** [comment]
A fresh get of the codebase fixed this issue so I'm guessing that this is a renv not cleaning up the library issue - thanks!

**Comment by jimhester** [comment]
ok, glad you have it sorted!

**Comment by QuLogic** [comment]
At this point, the `check_installed` means that `pkgload` now requires `rlang` >=0.4.10 since that's when that was added. But only when compiling, I guess?
