### ISSUE TITLE
R hangs after second `load_all()` call

### ISSUE THREAD

**Issue by ikosmidis** [r-lib/pkgload#155]
To reproduce with a package currently on CRAN get the source for **biglm** from <https://cran.r-project.org/src/contrib/biglm_0.9-2.1.tar.gz>, unpack and try `load_all()` at the **biglm** source directory twice (the first call will be fine).

I experimented with combinations of `load_all()` arguments but the behaviour has been the same. 

Any ideas where this behaviour comes from?

Thanks,
I

**Comment by jimhester** [comment]
Sorry, I can't reproduce this behavior, loading biglm multiple times works as intended on my machine without any hang.

**Comment by ikosmidis** [comment]
Thanks for checking. That's correct; I just tried to reproduce it on Windows 10 and ubuntu 20.04 machines and I could not. The behaviour happens on both macOS (Big Sur) systems I have access to, so most probably something is broken in both. Closing and will post any comments if I get around this.

**Comment by jimhester** [comment]
I would investigate uninstalling and reinstalling XQuartz on those machines, there were some versions recently that popup a window asking to upgrade, and if this happens in the background (e.g. if XQuartz was loaded implicitly by a package) your R session will hang indefinitely.

**Comment by ikosmidis** [comment]
Just done that; indeed that seemed to be the issue. Many thanks!
