### ISSUE TITLE
load_depends() fails if the package cannot be loaded without attaching it

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgload#156]
Somewhat surprising, but you can have packages like this, see e.g. https://github.com/r-lib/roxygen2/issues/1224

The problem is that `load_depends()` tries to load the package first, to check the version, without attaching it, and that already fails for these packages.

**Comment by jimhester** [comment]
PackageB is IMHO broken, it should not call `helloA` from PackageA without either importing it from PackageA or qualifying it with `::`. I don't think this is something we would really spend resources fixing.

**Comment by gaborcsardi** [comment]
Yeah, it is also a check failure if you don't import anything:

> ```
> Package in Depends field not imported from: ‘PackageA’
> These packages need to be imported from (in the NAMESPACE file)
> for when this namespace is loaded but not attached.
> ```

**Comment by jimhester** [comment]
Oh, good call, I think this is just a wontfix then.
