### ISSUE TITLE
Propagate error message from failed requireNamespace call

### ISSUE THREAD

**Issue by tlapak** [r-lib/pkgload#160]
or suggest calling it in the error message.

I spent some time tracking down the reason for `devtools::test()` failing with a warning that `plotly` was not available. My package imports `plotly` which was freshly installed. However, one of its dependencies was built under R 3.x so the call to `requireNamespace` in `check_dep_version` failed. Since `install.packages()` did not check this conflict I was left stumped.

**Comment by lionel-** [comment]
IIUC, you can pass `quiet = FALSE` to get this message.
