### ISSUE TITLE
load_all to a namespace instead of globalenv

### ISSUE THREAD

**Issue by mlell** [r-lib/pkgload#165]
I have an analysis script and multiple packages with utility functions develop along with it. I use `load_all` to quickly test the results of a change quickly in a util function. This has the big advantage of being quick so that I don't need to continuously switch contexts back and forth from science to R environment administration, helping me focus and maintain order in my util functions at the same time. 

However, as the number of functions and packages grows, I started using qualified function names in the form of 

```{r}
util <- loadNamespace("my.institute.util.pkg1")
util$my_util_function()
```

So I abbreviate the long package names and can still use qualified function names by this. With the advent of the [box](https://cran.r-project.org/web/packages/box/index.html) package, the pattern is very similar.

But this does not work anymore with `load_all()`, because this function loads to the global environment and I need to remove the namespace qualifier before testing my function. Possible but a nuissance. 

Can there be a function that works similarly to `loadNamespace` but the arguments are the same like  `load_all()`?

**Comment by jimhester** [comment]
```r
util <- pkgload::load_all()$env
util$my_util_function()
```

**Comment by mlell** [comment]
Thanks for this suggestion @jimhester, this already solves a lot of the problem! Also, executing `loadNamespace()` after `load_all()` seems to keep the new version of the namespace. This makes it already quite usable. If `load_all` could provide an option to not attach anything (besides the current options to attach all or only the exported names), this use case would be covered completely.
