### ISSUE TITLE
should load_all() also define .packageName variable?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgload#174]
When a package is built, R defines the `.packageName` variable potentially for use in the package. Should `load_all()` also provide this definition?

**Comment by jimhester** [comment]
Not in the global environment, I mean in the environment of the loaded package, e.g.
``` r
env <- devtools::load_all("~/p/devtools")
env$env$.packageName
#> [1] "devtools"
```

<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
I see what you mean now. That indeed appears to be functioning as expected. Sorry for the noise.
