### ISSUE TITLE
`dev_topic` does not handle images in Rd

### ISSUE THREAD

**Issue by netique** [r-lib/pkgload#186]
Hi,

I use `lifecycle` badges in my package and often call `load_all` to peek an Rd topic. However, the badge image is not rendered in Rd preview:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/34926852/147827770-71022e87-a163-4854-90b1-5bbb1dbef87d.png">

This is because the file does not exist.

**Comment by lionel-** [comment]
Have you called `usethis::use_lifecycle()` to add the SVGs to your `man/` folder?

**Comment by netique** [comment]
Sure, SVGs are there.

**Comment by hadley** [comment]
This is a known issue with the dev doc rendering; you'll need to build and re-install the package to check these images.
