### ISSUE TITLE
pkgload 1.2.3 broke `load_all()` with lubridate's usage of S4

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgload#196]
I don't think lubridate is doing anything particularly strange with S4, but you can no longer call `load_all()` twice. This worked before 1.2.3, so it seems like something in that release broke this.

If you clone lubridate locally, you should be able to reproduce by running `load_all()` twice. I see this with CRAN pkgload:

```r
> devtools::load_all(".")
ℹ Loading lubridate
> devtools::load_all(".")
ℹ Loading lubridate
Error in getClass(Class, where = topenv(parent.frame())) : 
  "Period" is not a defined class
```

**Comment by lionel-** [comment]
I can't reproduce this, do you have the latest version installed?

**Comment by DavisVaughan** [comment]
It reproduces with CRAN pkgload but not with dev pkgload. Now I'm curious how it got fixed

**Comment by lionel-** [comment]
hmm possibly #153

**Comment by DavisVaughan** [comment]
That fix was in 1.2.1 though, this didn't start until 1.2.3

**Comment by DavisVaughan** [comment]
I've at least managed to figure out where it is coming from.

https://github.com/tidyverse/lubridate/blob/0bb49b21c88736240219dc67e7ed0eb3df15d9b1/R/vctrs.R#L8-L9

We used `delayedAssign()` here to create some shared empty lubridate S4 objects for use in the tests. I _faintly_ remember having to do it this way because we couldn't create these objects in `.onLoad()` because of the way S4 worked, but I might be wrong.

**Comment by DavisVaughan** [comment]
The error used to happen in `unregister_namespace()` here:
https://github.com/r-lib/pkgload/blob/df5d161106844f2e1bbf3d0ddfc5637d636ead88/R/namespace-env.r#L249

If you did `debugonce()` and got to that line, then you could run:

```r
xx <- ns_env("lubridate")

xx$lubridate_shared_empty_period
```

and that would reproduce the error.

But now in the dev version that doesn't error anymore.

Does that jog anything in your memory?

**Comment by lionel-** [comment]
_Possibly_ #157

**Comment by DavisVaughan** [comment]
Interesting, ok well thanks for tracking it down. Glad we at least have a PR to refer back to if it somehow comes up again
