### ISSUE TITLE
quiet = TRUE no longer works

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgload#213]
```
> pkgload::load_all(quiet = TRUE)
ℹ Loading pkgload.
> pkgload::load_all(quiet = TRUE)
ℹ Loading pkgload.
```

I tried to fix this in `load_all_quiet()` but I don't understand the logic there.  Maybe `quiet` needs to be set to `NULL` by default in order for this more complex logic to work?

**Comment by lionel-** [comment]
The selective override needed a trailing `%||% quiet`. I've added comments and improved the naming to make the logic easier to follow.
