### ISSUE TITLE
pkgload::system.file is too restrictive

### ISSUE THREAD

**Issue by mikapfl** [r-lib/pkgload#216]
Hi,

In a testing environment, if one does

```r
r$> devtools::load_all()
ℹ Loading packageName

r$> system.file('inst/filename', package="packageName")
Error in `system.file()`:
! Paths can't start with `inst`
ℹ Files in `inst` are installed at top-level.
Run `rlang::last_error()` to see where the error occurred.
```

the `system.file` shim will throw an error. However, this is not what happens in normal operation. If I do

```r
r$> devtools::install('.')
r$> library(packageName)
r$> system.file('inst/filename', package="packageName")
[1] ""
```

there is no error and I get back an empty string. This is especially annoying if `mustWork = FALSE` (the default) which can be used to test for files that might be non-existent.

Relevant context: #104 https://github.com/r-lib/pkgload/commit/c923564cd93d468e3cbb2fd7a37c2ab9b363fa95

On the one hand, this breaks some of our workflows in tests, and on the other hand there is the (maybe distant) possibility that someone wants to ship something under `inst/`, i.e. in `inst/inst/` in the source tree, which is then inaccessible when loaded via `load_all`.

Best regards,

Mika

**Comment by lionel-** [comment]
I think we can just say that pkgload doesn't support `inst/inst` paths, so that it can helpfully throw an error when (what appears to be) a common mistake is detected?
