### ISSUE TITLE
`export_all` does not export all

### ISSUE THREAD

**Issue by dheimgartner** [r-lib/pkgload#218]
Hi!

I am on an ubuntu 20.04.4.

After updating `pkgload` from 1.2.4 to 1.3.0 the function `pkgload::load_all` does not export all objects. Actually, I am using `devtools::load_all` (but this calls `pkgload::load_all` which causes the trouble as described below).

For example: I am writing a package named `my_pkg` where I have the function `my_func` in the R repo. After running `devtools::load_all()` and then calling `my_pkg::my_func()` I get the error

`Error: 'my_func' is not an exported object from 'namespace:my_pkg'`

However, calling the function without package reference (i.e. `my_func()`) works. And printing the source of `my_func` in the console mentions that `<environment: namespace:my_pkg>`...

Downgrading to pkgload 1.2.4 resolves this issue...

Regards
Daniel

**Comment by lionel-** [comment]
This is a consequence of #212. I would say the new behaviour is more correct. Why do you want to use `::` instead of `:::`? The former will never work with the installed version.

**Comment by dheimgartner** [comment]
`my_func()` in my example above is not an internal function (it has just not yet been exported). So in my package (while developing) I might use `my_pkg::my_func()` in the source of other functions to signal that the function is actually from the package. However, now, this will no longer work unless I export the function (e.g. with the roxygen `@export` tag and `devtools::document()`) or use `:::` (which might be inconsistent because it is not an internal function)... Of course I can easily do this - I was just wondering because it worked before the update...

**Comment by lionel-** [comment]
It worked before the update because we exported everything including internal functions, which caused issues in some cases. The current behaviour is correct I think.
