### ISSUE TITLE
Warning in install.packages

### ISSUE THREAD

**Issue by Molina-Valero** [r-lib/pkgload#232]
Dear mainatiner,

I obtain the following issue when I try to install the package:

Warning in install.packages :
  installation of package ‘pkgload’ had non-zero exit status

I am using the last version of R and RStudio. Do you know if this issue is being common? Because it is the first time that it happens to me.

Thank you in advance,
Juan Alberto

**Comment by lionel-** [comment]
This issue can be due to a number of things, likely unrelated to pkgload itself. This is likely an admin/user issue. Also there should be more error output to help you figure it out. The message reported here is not sufficient to understand what happened.
