### ISSUE TITLE
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 

### ISSUE THREAD

**Issue by lilyLlily** [r-lib/pkgload#233]
install.packages("devtools")
install.packages("pkgload")
I have already successfully installed 'pkgload',while the system alarms that 'pkgload' does not exist, when I want to install 'devtools'. What should I do?

**Comment by lionel-** [comment]
Please post a full output.

**Comment by lilyLlily** [comment]
_i try to run the code as follow_
install.packages("digest")
install.packages("devtools")
install.packages("pkgload")
devtools::insatll_github("immunogenomics/harmony")
library("harmony")

hower i recive 

>install.packages("pkgload")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
trying URL 'https://cran.rstudio.com/src/contrib/pkgload_1.3.2.tar.gz'
Content type 'application/x-gzip' length 76704 bytes (74 KB)
downloaded 74 KB
Error: object 'myPaths' not found
Execution halted

> devtools::insatll_github("immunogenomics/harmony")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  the package ‘pkgload’ dose not exist

**Comment by lionel-** [comment]
Sorry I dropped the ball on this, hopefully you found how to fix this problem since then.
