### ISSUE TITLE
library(pkg) throws error if pkg depends on a package loaded with load_all() 

### ISSUE THREAD

**Issue by ethanplunkett** [r-lib/pkgload#235]
I'm working on a package "DoStuff" that uses a data package "Stuff".  Stuff is really big and used for example data.
DoStuff's DESCRIPTION file suggests Stuff as it's not needed to use the package. 
Stuff's DESCRIPTION file depends on DoStuff as the object in it is of a class defined in DoStuff.

Running, in a clean session:
```{r}
devtools::load_all(".")  # on DoStuff 
library(Stuff) 
```
Results in an error: 
"Error: package ‘DoStuff’ required by ‘Stuff’ could not be found."

The traceback is:
3: stop(gettextf("package %s required by %s could not be found", 
       sQuote(pkg), sQuote(pkgname)), call. = FALSE, domain = NA)
2: .getRequiredPackages2(pkgInfo, quietly = quietly)
1: library(Stuff)

The problem is that base::.getRequiredPackages2() doesn't play nicely with packages loaded with load_all().  Specifically  [line 841](https://github.com/SurajGupta/r-source/blob/master/src/library/base/R/library.R) calls a locally defined (line 828) function ".findVersion"  which calls system.file() on "DoStuff" and fails. 

The code below mimics the failure point.  Loading a package with 
load_all causes system.file() called on the same package - from code outside of the package - to fail to find the package's metadata file. 

In a clean R session:
```{r}
devtools::load_all(".") # on DoStuff 
lib.loc <- .libPaths()
system.file("Meta", "package.rds", package = "DoStuff", lib.loc = lib.loc)  
# returns empty string: ""
```
Here's the same example but setup for running when your working directory
is set to pkgload's source.  I haven't tested this but assume it will be easy for you to and that the behavior will be the same:
```
devtools::load_all(".") # On pkgload
lib.loc <- .libPaths()
system.file("Meta", "package.rds", package = "pkgload", lib.loc = lib.loc)
# I expect this to return: ""
```

In constrast if library() is used a path is returned:
With DoStuff:
```{r}
library(DoStuff) # on DoStuff
lib.loc <- .libPaths()
system.file("Meta", "package.rds", package = "DoStuff", lib.loc = lib.loc)
# Returns a path to a file: ".../DoStuff/Meta/package.rds
```
Or with with pkgload  (again not tested):
```{r}
library(pkgload) # 
lib.loc <- .libPaths()
system.file("Meta", "package.rds", package = "pkgload", lib.loc = lib.loc)
# Returns a path to a file: ".../pkgload/Meta/package.rds
```
This is admittedly not a huge problem.  If I call library(Stuff) prior to load_all() I can avoid it.  Also, if I switch Stuff to the imports field of DoStuff I think I would never encounter this - but Stuff is big so I don't want  to do that.  

I know you already have a shim for for system.file() but suspect the problem is that package.rds doesn't exist in the source package.  I don't know what the solution is.  A kluge would be for the shim version of system_file() to create a mock Meta/package.rds file and then return its path.

**Comment by lionel-** [comment]
> This is admittedly not a huge problem. If I call library(Stuff) prior to load_all() I can avoid it. Also, if I switch Stuff to the imports field of DoStuff I think I would never encounter this - but Stuff is big so I don't want to do that.

yup it seems like fixing that would be more effort than worth it. So I suggest we close until this becomes a stopper for some kind of workflow. Thanks for the report!
