### ISSUE TITLE
Development documentation doesn't show in RStudio (R 4.3.0 alpha)

### ISSUE THREAD

**Issue by pbreheny** [r-lib/pkgload#238]
Since upgrading to R 4.3.0 alpha and RStudio 2023.03.0, the development documentation no longer shows up in the RStudio help pane. Specifically, after running pkgload::load_all(), then requesting a help file (e.g., ?make_graph), I get the usual

```
Rendering development documentation for "make_graph"
```

But the help pane displays

```
Error in .get_package_metadata(pkgdir) : Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.
```

I have tried this on three different packages, same thing happens every time. This works fine in R (outside of RStudio), so I thought it was an RStudio problem and opened an issue there: rstudio/rstudio#12945. But thought I would mention it here as well.

**Comment by pbreheny** [comment]
Just FYI, I can further confirm that the issue appears to be specific to R 4.3.0 alpha -- if I load R version 4.2.3 on the same machine (running Ubuntu 20) and same RStudio installation (2023.03.0), everything is fine.

**Comment by psychelzh** [comment]
Also confirmed in 4.3.0 release version.

**Comment by lionel-** [comment]
I'm seeing this backtrace which suggests this is an RStudio issue:

```
traceback()
#> 5: stop("Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.")
#> 4: .get_package_metadata(pkgdir)
#> 3: tools::loadPkgRdMacros(file.path(R.home("share"), "Rd", "macros",
#>        "system.Rd"), macros = macros)
#> 2: .rs.RdLoadMacros(file)
#> 1: .rs.Rd2HTML("/Users/lionel/Sync/Projects/R/r-lib/pkgload/man/load_all.Rd",
#>        "pkgload")
```

It looks like this is from https://github.com/r-devel/r-svn/commit/25f168af00e723bc4eb2d43501e79250cda28ae1 which now fails when a `DESCRIPTION` file is absent. This call was added to RStudio in https://github.com/rstudio/rstudio/pull/12111

**Comment by pbreheny** [comment]
I'm going to go ahead and close this, as it seems to have been an RStudio issue that is now resolved.
