### ISSUE TITLE
pkgload 1.3.0 breaks initializing NAMESPACE with roxygen?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/pkgload#239]
I think {pkgload} 1.3.0 breaks the workflow of initializing a NAMESPACE file with roxygen2.

I wasn't able to install the dev version of {roxygen2}, but can reproduce with CRAN roxygen2 and dev {pkgload}.

```r
ns_file = "ggplot2/NAMESPACE"
local({
  ns = readLines(ns_file)
  on.exit(writeLines(ns, ns_file))
  file.remove(ns_file)

  roxygen2::roxygenize("ggplot2")
})
```

fails:

```
ℹ Loading ggplot2
Error in `load_all()`:
! Failed to load R/geom-.R
Caused by error in `list2()`:
! could not find function "list2"
Run `rlang::last_trace()` to see where the error occurred.
```

I believe 19de671ec778e55064272f2fab68e3d979a87c74 is where the behavior changed.

We don't store NAMESPACE files, instead always generating them on the fly with `roxygenize()`.

I chose {ggplot2} because I noticed this in the context of a small package wrapping a dataset like so:

```r
#' A data set
#'
#' @format A `data.frame` with N observations of P variables:
#'   * `col1`, desc1
#'   * `col2`, desc2
"my_data"
```

And trying to update pkgload 1.2.4 ➡️ 1.3.3 was failing with `my_data` not found during roxygenize.

**Comment by MichaelChirico** [comment]
Oh, maybe this already wasn't working in 1.2.4... after `git checkout v1.2.4`, I get essentially the same error:

```r
roxygen2::roxygenize(".")
# ℹ Loading ggplot2
# Error in list2(...) (from ggproto.R#60) : could not find function "list2"
```

**Comment by MichaelChirico** [comment]
Might be an issue on the {roxygen2} side (https://github.com/r-lib/roxygen2/issues/1144)?

**Comment by hadley** [comment]
Yeah, looks like a roxygen2 issue. I guess I don't really understand how you expect this to work, since removing the `NAMESPACE` obviously removes any import declarations.

**Comment by MichaelChirico** [comment]
> removing the NAMESPACE obviously removes any import declarations.

Right, but they're all listed as `#' @import` / `#' @importFrom` entries... I'll follow up more in {roxygen2} comments.
