### ISSUE TITLE
Somehow French translation not working in test suite

### ISSUE THREAD

**Issue by tillea** [r-lib/pkgload#264]
Hi,
I intend to upgrade the Debian packaged pkgload.  We are running the test in this [script](https://salsa.debian.org/r-pkg-team/r-cran-pkgload/-/blob/master/debian/tests/run-unit-test) which boils down to

    cd tests
    LC_ALL=C.UTF-8 R --no-save < testthat.R
    LC_ALL=C.UTF-8 R --no-save < wipe.R

Unfortunately this results in two failures which you can see inside the [full test log](https://salsa.debian.org/r-pkg-team/r-cran-pkgload/-/jobs/4810637#L399) which says:

    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-po.R:7:3'): translation domain correctly loaded ──────────────
    with_lang("fr_FR", "fr", hello()) (`actual`) not equal to "Bonjour" (`expected`).
    `actual`:   "Hello"
    `expected`: "Bonjour"
    ── Failure ('test-po.R:36:3'): modified translations are correctly reloaded ────
    with_lang("fr_FR", "fr", hello()) (`actual`) not equal to "Salut" (`expected`).
    `actual`:   "Hello"
    `expected`: "Salut"
    [ FAIL 2 | WARN 3 | SKIP 15 | PASS 342 ]

I see a chance that this is due to the fact how we are calling the test.  However, this was working nicely until version 1.3.2.1 but fails now with version 1.3.3.

Kind regards, Andreas.

**Comment by tillea** [comment]
Ping?

**Comment by tillea** [comment]
I've added your last two patches to the packaging and this works now.  Thanks a lot, Andreas.

**Comment by lionel-** [comment]
Now on CRAN!
