### ISSUE TITLE
add a debug argument to load_all()

### ISSUE THREAD

**Issue by mcol** [r-lib/pkgload#301]
I've spent quite some time trying to understand why, when compiling some C++ code with `devtools::load_all()`, I would always get the `g -O0` flags (among others) at the very end, thus overriding my preferred settings in `~/.R/Makevars` or `src/Makevars`. Eventually I've worked out that these are appended by `pkgbuild::compile_dll()`, which is called by `pkgload::load_all()`.

I think the current default makes sense, but it would be nice if `pkgload::load_all()` had a `debug` flag that gets passed to `pkgbuild::compile_dll()`, so that the debug options could be disabled easily. Alternatively, `load_all()` could accept a `...` argument and pass that to `compile_dll()` (this seems to me an inferior solution though).

**Comment by gaborcsardi** [comment]
FWIW you can also set the `pkg.build_extra_flags` option or the `PKG_BUILD_EXTRA_FLAGS ` env var for pkgbuild, see https://github.com/r-lib/pkgbuild#options
