### ISSUE TITLE
`load_all()` adds NAMESPACE imports to the search path

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgload#38]
- [ ] Function imports `importFrom(glue, glue)`
- [ ] Package imports `import(ggplot2)`

**Comment by gaborcsardi** [comment]
Would these go in an extra namespace? I.e. you would basically put the import namespace on the search path?

**Comment by jimhester** [comment]
That is an option, main worry would be cleaning it up I guess. 

My thought was to tweak `setup_ns_exports` to include the import objects as well.
