### ISSUE TITLE
Feature Request: Find Minimum Version of Required Packages

### ISSUE THREAD

**Issue by billdenney** [r-lib/pkgload#42]
Hello,

I'm trying to find the right home for this feature within the devtools universe...  I initially submitted it at hadley/devtools#1484.  When I looked into the devtools diaspora, I think that this is the right place.  Please let me know if you agree:

I've recently experienced an issue with my PKNCA package where I didn't know that a new feature I added had a minimum required version of a package in the Imports list.  I'd like to propose a new feature of devtools that will take a list of packages and install them to look for the version number of dependencies where tests fail.  It would then indicate that the next version is the required version.

A potential interface could be:
```r
find_required_dep_version(pkg=".", which_set=c("Depends", "Imports", "Suggests"), which_library, repo=getOption("repos"), ...)
```

It would then search on CRAN (or potentially other repository types) installing dependency packages one-by-one back in time until tests fail.

If this would be of interest, I can generate a pull request.

**Comment by hadley** [comment]
This definitely doesn't belong in pkgload - pkgload is exclusively to do with the part of `load_all()` part of devtools (which is quite complicated).

Sorry if I didn't make it clear in my original response, but I don't think there's any existing package that is should be part of. It feels like it's enough to be it's own package, especially if you imagine extending it to minimum versions of R as well.
