### ISSUE TITLE
Recompile everything when file in subfolder has changed

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgload#50]
That would be useful for unity builds. The rlang C sources are now in a subfolder (https://github.com/tidyverse/rlang/tree/master/src/rlang) and the C files are included from a single file https://github.com/tidyverse/rlang/blob/master/src/rlang.c.

This has several advantages:

- it is easy to copy that subfolder within another package
- the entire compilation happens in a single compilation unit. This is less verbose (which is nicer when there are many files) and much faster.
- including from a master C file is easier than defining a makefile.

However changing a file in a subfolder doesn't trigger a recompilation because the files it contains are not tracked for changes. @hadley suggested to always recompile when a subfolder file changes.

The overhead of recompiling everything shouldn't be an issue since unity builds are fast. Also this shouldn't affect most packages because using subfolders is rare.

**Comment by jimhester** [comment]
I don't really think encouraging this form of code organisation is one we should endorse or support. There are a [number of issues](http://altdevblog.com/2011/08/14/the-evils-of-unity-builds/) with unity builds and I don't think they are the right solution for R packages. Compiling without optimization, parallel make and ccache are sufficient to make my builds during development nearly instantaneous.

**Comment by lionel-** [comment]
I don't think the problems mentioned in that article are an issue in practice. E.g. I would avoid file local variables altogether. And you have the flexibility of adding a compilation unit if needed. If you have a C project or avoid heavily templated C++ code than unity builds are pretty much instantaneous so rebuilding each time is not an issue.

I haven't switched to an unity build for speed purposes but as an easy way of organising code in subfolders. I also like to be able to split the code in many files without adding verbosity when reloading. Perhaps there is an easy alternative I am missing?

**Comment by jimhester** [comment]
There is a quiet option to `devtools::load_all()` and `pkgbuild::compile_dll()` which silences the build output.

**Comment by lionel-** [comment]
I will continue experimenting with the unity build. In general I think programmers over-emphasise issues of encapsulation. I don't exclude getting burned by this mindset one day ;)

**Comment by hadley** [comment]
Unfortunately this issue should actually belong in pkgbuild.  

And I think maybe you'll need to do a PR. The code to check out is:

```R
sources <- function(path = ".") {
  srcdir <- file.path(path, "src")
  dir(srcdir, "\\.(c.*|f)$", recursive = TRUE, full.names = TRUE)
}
```

It looks like the intent is to scan recursively, so you'll probably need to do a little debugging on your end to figure out what the problems is (it's possible that `recursive` only applies after `pattern` selects files)
