### ISSUE TITLE
Use rstudioapi to save open files

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgload#52]
In `load_all()`

Alternatively, we could call `load_all()` something more descriptive here, and then in devtools `load_all()` would become a wrapper in the same way that `test()`, `document()` etc are.

**Comment by jimhester** [comment]
I think saving the open files should probably happen in `devtools::load_all()` rather than here and we can rename `pkgload::load_all()` if we need to, although I don't think it is that confusing if they have the same name.

**Comment by hadley** [comment]
Yeah, it's probably fine. I don't think many people are going to `library(pkgload)`.
