### ISSUE TITLE
Environment of helper functions

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgload#55]
The environment of the functions defined in testthat helpers seems to be the package environment, not the namespace environment. Is this by design?

``` r
devtools::load_all("~/git/R/tibble")
#> Loading tibble
environment(output_file)
#> <environment: package:tibble>
#> attr(,"name")
#> [1] "package:tibble"
#> attr(,"path")
#> [1] "/home/muelleki/git/R/tibble"
```

This means that I can't currently use `mockr::with_mock()` in a function defined in a helper. No big deal, but took some time to find out.

(Currently `pkgload::load_all()` doesn't seem to run helpers for me...)

**Comment by jimhester** [comment]
Are you using the current HEAD? This was changed recently https://github.com/r-lib/pkgload/commit/b2c80bc9c941dfdbab987de0c442b4f84ecea53b

**Comment by jimhester** [comment]
As of https://github.com/r-lib/pkgload/commit/80a649330317a3e8426a94acd33c82011c31b90d this seems to do what you expect.

``` r
pkgload::load_all("~/p/tibble")
#> Loading tibble
environment(output_file)
#> <environment: namespace:tibble>
```

**Comment by krlmlr** [comment]
Thanks, great that helpers are now defined in the package namespace. I'm seeing that the helpers are only exported with `export_all = TRUE`, looks good to me.
