### ISSUE TITLE
Can't install pkgload

### ISSUE THREAD

**Issue by friendly** [r-lib/pkgload#58]
You may know this, but `pkgload` can't be installed from github.  This blocks me from installing `pkgdown`

    > devtools::install_github("r-lib/pkgload")
    Downloading GitHub repo r-lib/pkgload@master
    from URL https://api.github.com/repos/r-lib/pkgload/zipball/master
    Installing pkgload
    "C:/R/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
      --quiet CMD INSTALL  \
      "C:/Users/friendly/AppData/Local/Temp/Rtmp23AVmF/devtools145864e75f23/r-lib-pkgload-7fd5f55"  \
      --library="C:/R/R-3.4.1/library" --install-tests 

    * installing *source* package 'pkgload' ...
    ** R
    ** tests
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    Error: package or namespace load failed for 'pkgload':
     .onLoad failed in loadNamespace() for 'pkgload', details:
      call: is_null(x)
      error: object 'rlang_is_null' not found
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing 'C:/R/R-3.4.1/library/pkgload'
    Installation failed: Command failed (1)
    >

**Comment by jimhester** [comment]
This likely has to do with the versions of devtools / rlang you have installed rather than an error in pkgload itself. Please provide the results of `sessioninfo::session_info()` to help debug this.

**Comment by ChrisMuir** [comment]
FWIW, I was having the exact same failure and error message as @friendly on a PC.....I had the dev version of `rlang` installed, what fixed the `pkgload` issue for me was simply installing the stable release of `rlang` from CRAN. 

Here's my `sessionInfo`, after installing `rlang` from CRAN and then installing `pkgload` from GitHub via `devtools`:
```r
sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2        tools_3.4.2     withr_2.0.0     curl_3.0        yaml_2.1.14     memoise_1.1.0   knitr_1.17     
[10] git2r_0.19.0    digest_0.6.12   devtools_1.13.3
```

**Comment by friendly** [comment]
I can confirm that this is a version issue, but can't trace it as exactly as @ChrisMuir because I was in an airport lounge working on my 2nd IPA.  I reinstalled the latest version of `devtools` from GitHub, and then tried to reinstall `pkgdown` from GitHub.  It worked!

Given the current flux in the `devtools` breakout into smaller packages, a note somewhere in the READMEs might be helpful.
