### ISSUE TITLE
Update imports environments on load_all

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgload#59]
Would it make sense to update the imports environments of all loaded packages when a package is reloaded with `load_all()`? Currently these imports are scoped in a dangling namespace.

This is particularly problematic when `.Call()`ing dangling function pointers e.g. https://github.com/r-lib/testthat/issues/654.

This could be solved by searching through all imports envs for all functions scoped in the package namespace and update their closure envs with the new namespace.

**Comment by jimhester** [comment]
I have a WIP at https://github.com/jimhester/pkgload/tree/redo-imports that fixes this by re-creating the imports environment for all loaded packages that import functions from the package being loaded by pkgload.

I don't really love having the environment unlocking code in the branch. Simply updating the existing symbols to the new definitions should be enough for this case at least...

The current state does fix the issue however.

**Comment by lionel-** [comment]
thanks!
