### ISSUE TITLE
pkgload::unload() not compatible with devtools::unload()

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgload#62]
Is it on purpose that `pkgload::unload()` no longer handles a package path? Also no default argument for unloading the package currently being developed.

**Comment by jimhester** [comment]
Yes this was done on purpose, you can use `pkgload::unload(pkgload::pkg_name())` to unload the package in the current project root.

**Comment by lionel-** [comment]
Is this going to be a convention in post-diaspora devtools? This makes integration with IDEs more difficult.

**Comment by jimhester** [comment]
devel devtools just re-exports `pkgload::unload()`. I can make `unload()` have a default value of `pkg_name()` if it would help, then it should have the same behavior when called with no arguments as previously.

**Comment by lionel-** [comment]
Thanks this would be helpful.
