### ISSUE TITLE
Need a way to add shims to an already loaded package

### ISSUE THREAD

**Issue by wch** [r-lib/pkgload#69]
For example, when developing a new package that creates an htmlwidget, if you do `load_all()` on your package, then when your code calls `htmlwidgets::htmlwidget()`, it will no longer work. because it calls `system.file()` on your package -- but it needs the shimmed version of `system.file()` for this to work.

This is the workaround I currently use:
https://gist.github.com/wch/c942335660dc6c96322f

It would be nice if there were an easier way to shim this function (and possibly others) in an already-loaded package.

**Comment by cpsievert** [comment]
Note that htmltools also utilitizes `system.file()` and fails for similar reasons -- this is what you get if you have shiny loaded:

```r
library(htmltools)

a <- tags$a()
dep <- htmlDependency(
  name = "jq", 
  version = "1.0.0",
  package = "shiny",
  src = file.path("www", "shared", "jqueryui"),
  script = "jquery-ui.js",
  all_files = FALSE
)
browsable(attachDependencies(a, dep))
```

```r
Error in dirname(to) : a character vector argument expected
```

**Comment by ijlyttle** [comment]
Hi,

@jennybc referred me to this issue to raise the possibility that `fs::path_package()` could be used to address this problem (r-lib/fs#175). Also raising this in rstudio/leaflet#52.

I don't know well enough the internals of pkgload, htmtools, or htmlwidgets to offer any opinions, but I am happy to file issues in the right places, if you can suggest them 🙂

**Comment by lionel-** [comment]
Since the fate of `env_unlock()` is uncertain, I've just documented the `fs::path_package()` workaround for now. Hopefully it is sufficient. Closing this issue now but further discussion about this is always welcome if `path_package()` is not sufficient for your workflow.
