### ISSUE TITLE
could not find function

### ISSUE THREAD

**Issue by Dripdrop12** [r-lib/pkgload#71]
I have an internal function:
```
#' @keywords internal
#' @export
my_func <- function() {
  print("Hi!")
}
```
It's being called elsewhere:
```
#' @export
my_other_func <- function() {
  my_func()
}
```

When I run `devtools::load_all()` and call `my_other_func`, I am getting the following error:

```
Error in my_func () : 
  could not find function "my_func "
```
I've tried removing the `@export` tag and removing the `@keywords internal` tag from `my_func`, and running `document` to recreate the NAMESPACE, but nothing has worked. Am I missing something very basic here?

**Comment by jimhester** [comment]
It is hard to say without seeing the full context, but really make sure the file is actually in the `R/` folder with the right extension and there are no typos in the function name.

**Comment by Dripdrop12** [comment]
typo... omg
