### ISSUE TITLE
Default encoding is ASCII when Encoding is not specified in DESCRIPTION

### ISSUE THREAD

**Issue by jarodmeng** [r-lib/pkgload#86]
Currently default encoding is assumed to be ASCII ([commit link](https://github.com/r-lib/pkgload/commit/664abc6f41337c754805d1e2618b25c6e10d08b0)).

Is there a reason why default encoding is set to ASCII here? A lot of R files have non-ASCII characters (e.g., in comments or roxygen documentations). Parsing those files using ASCII encoding sometimes breaks and crash load_all().

FWIW, roxygen2 assumes UTF-8 when Encoding is not set.

**Comment by jimhester** [comment]
If you have non-ASCII encodings in your comments or documentation you need to set `Encoding` in the DESCRIPTION, otherwise your package will not install on systems that don't have your current system's encoding.

Using anything but ASCII is just kicking the can down the road and you will run into issues later on.

**Comment by jarodmeng** [comment]
Thanks for the quick reply! I've found 3 issues.

1. `load_code` passes `encoding` to `source_many` which in turn passes it to `source_one`. `source_one` uses `read_lines_enc` to read the files.

    It seems that `read_lines_enc` sets default encoding to `UTF-8` ([file link](https://github.com/r-lib/pkgload/blob/f2dfd69cb40b3b1bdafae51b513d24bad595bad5/R/enc.R#L1)) which is different from ASCII.

2. `read_lines_enc` passes `encoding` to `file`. `file` gets default encoding using `getOption("encoding")` which might be set by the end user even when `Encoding` is not set in `DESCRIPTION`. By using ASCII as default, pkgload basically ignores user's option setting.

    Furthermore, default `encoding` option is `native.enc` which corresponds to end user's locale. When nothing is set, `native.enc` might be the best bet on what the encoding should be rather than ASCII.

3. When user doesn't set `Encoding` in `DESCRIPTION` and includes non-ASCII characters in R files, the error thrown by pkgload happens in `parse` ([code link](https://github.com/r-lib/pkgload/blob/f2dfd69cb40b3b1bdafae51b513d24bad595bad5/R/source.r#L24)). The error messages indicates nothing about setting `Encoding` in `DESCRIPTION`, so it could take a while for the end user to realize what's actually wrong.
