### ISSUE TITLE
Don’t load already-loaded package in `load_all`

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/pkgload#92]
`devtools::test()` crashes with a very unhelpful “infinite recursion” error, because I wrap a function in `.onLoad`:

```r
backup_env <- new.env()
.onLoad <- function(...) {
    # running the following lines more than once means that
    # backup_env$utils_flush_console == utils::flush.console
    # and therefore calls itself infinitely
    backup_env$utils_flush_console <- utils::flush.console
    replace_in_package('utils', 'flush.console', function() {
        backup_env$utils_flush_console()
        my_flush_console()
    })
}
```

`.onLoad` should never be called twice, but pkgload (and therefore devtools) does exactly that.

Please make sure you don’t load an already-loaded package in `load_all`

**Comment by jimhester** [comment]
You should be removing your shim in `.onUnload()` then, this is not a bug in pkgload.
